apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/heitorfreitasferreira/todolist-app
    newTag: 82b98bff2c79930e623bf7b69d4cac02b470e272
    digest: sha256:af65aa175a616caa08ab287f6542cc8397bc3b1c7600ddcf9b346ce4e6b980b4
