apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todolist
spec:
  rules:
    - host: prod.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todolist
                port:
                  number: 80
