apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todolist-production
resources:
  - ../../base
  - namespace.yaml
  # SealedSecrets (gerados com kubeseal --scope strict, um por env):
  - sealed-postgres.yaml
  - sealed-auth.yaml
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: todolist-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: todolist
images:
  - name: ghcr.io/heitorfreitasferreira/todolist-app
    newTag: b44308a4ade1c587880652f3342dcc99e9666925
    digest: sha256:960dba0e26e74d799e8abcf71e149d58f562f5b4b317500eb99f9965dc7969ef
