apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todolist-production
resources:
  - ../../base
  - namespace.yaml
  # SealedSecrets (gerados com kubeseal --scope strict, um por env):
  - sealed-postgres.yaml
  - sealed-auth.yaml
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: todolist-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: todolist
images:
  - name: ghcr.io/heitorfreitasferreira/todolist-app
    newTag: 7bfafa351a859e21d50a5bae77d299e64ebbb1cf
    digest: sha256:c345118781747b3011a79bc5fc9c3703469cd9331465856b25bb80201632289c
